version: '3.1'

services:

  app:
    image: ghcr.io/ravitejalam/splitwise-analytics:latest
    ports:
      - "8000"
    env_file:
      - .env

  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app