name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          DOCKER_VERSION=$(cat VERSION)
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$DOCKER_VERSION .
          docker tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$DOCKER_VERSION ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$DOCKER_VERSION
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
