name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag name
        id: tag_name
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Build and push Docker image
        if: steps.tag_name.outputs.version != ''
        run: |
          DOCKER_VERSION=${{ steps.tag_name.outputs.version }}
          docker build -t ghcr.io/${{ github.repository }}:$DOCKER_VERSION .
          docker tag ghcr.io/${{ github.repository }}:$DOCKER_VERSION ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:$DOCKER_VERSION
          docker push ghcr.io/${{ github.repository }}:latest
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
